# docs:
# http://rubocop.readthedocs.io/en/latest/cops_style/
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
Metrics/LineLength:
  Max: 99

Documentation:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
